### ISSUE TITLE
Update PDF metadata feature request

### ISSUE THREAD

**Issue by OUsteventhomas** [sevein/guggmeta#12]
Your GO script is able to pull pdf metadata from an existing pdf file, would it be possible to add the capability to update that metadata into the file as well?  Something similar to PyPDF2.

Feel free to close this if i posted in the wrong spot for a feature request.

**Comment by sevein** [comment]
Sorry @OUsteventhomas, that's not possible and I'm not planning to work on that feature. Thank you!
